### ISSUE TITLE
sha256 change on 1.16

### ISSUE THREAD

**Issue by alexmace** [tcltk/tcllib#4]
Installs of tcllib via homebrew are now failing because the tarbal for 1.16 no longer matches the SHA-256 hash: https://github.com/Homebrew/homebrew-dupes/issues/465

Has this been legitimately been retagged, so the sha needs updating, or is something nefarious going on? I can't see any evidence of retagging.

**Comment by andreas-kupries** [comment]
Hello Alex, and apologies for the inconvenience.
Yes, that re-tag is legitimate.

In summary, a recent report about a bug which was fixed in 2013 gave rise to a journey at the end of which fossil's exporter to git was fingered as having trouble and generating a bogus fast-export dump. A comparison of the __fossil trunk head__ vs the generated __git master head__ showed 68 files and dirs __missing__ from git in that revision.

The issue was semi-solved by doing a __fossil rebuild__ on the master repository. At that point the exported git dump was OK, containing everything. A consequence of that was however pretty much all tags and branches are now pointing to different commits/shas, with the full data they should have. This includes the release tags going back to 1.15.

I call this "semi"-solved because while the export is now ok I do not know what was broken in the exporter to cause the problem, and so it may reappear. I only suspect that some schema change left state data for the exporter in a bad state, but not bad enough to cause a warning or abort. I am still mulling in the back of my mind how to code something to detect such a mismatch in the future and alert me.

And I still have to go over the other mirrored repos, like tklib, etc. (All under the tcltk org) and regenerate them, in case they have the equivalent problem. So, you can expect similar changes for these in the near future. How can I contact you when this is done, to give you the necessary FYI ?
(Or any other maintainers of homebrew recipes for these repos ?)

You can see more of the gory details in the tickets https://core.tcl.tk/tcllib/info/ad52568aab98ec49 and https://core.tcl.tk/tcllib/info/d36555bc472c8243 at the main site.

**Comment by alexmace** [comment]
Thanks for the explanation - I'm not actually the maintainer of the tcllib formula for Homebrew, I just ran into the issue reported in the bug and saw a suggestion to report it upstream, which no one had done, so I did it. But now we know, thanks!
